name: core
services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: core-npm
    ports:
      - 80:80
      - 443:443
    volumes:
      - /fjellheimen/data/core/npm/data:/data
      - /fjellheimen/data/core/npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/stacks/.env
    healthcheck:
      test:
        - CMD
        - /bin/check-health
      interval: 10s
      timeout: 3s
    restart: unless-stopped
  dockge:
    image: louislam/dockge:latest
    container_name: core-dockge
    user: 1000:1000
    group_add:
      - "996"
    volumes:
      - /fjellheimen/data/core/dockge:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /fjellheimen/stacks:/fjellheimen/stacks
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/stacks/.env
    environment:
      - DOCKGE_STACKS_DIR=/fjellheimen/stacks
    restart: unless-stopped
networks:
  proxy-network:
    name: proxy-network
